#!/bin/bash
# =============================================================================
# AEGIS-SIGHT - PR 自動生成スクリプト
# ClaudeOS WorkTree 連動で呼び出される
# =============================================================================

set -euo pipefail

REPO="Kensan196948G/AEGIS-SIGHT"
BRANCH=$(git branch --show-current)
BASE_BRANCH="${1:-main}"

if [ "$BRANCH" = "main" ]; then
  echo "[ERROR] Cannot create PR from main branch."
  exit 1
fi

echo "[ClaudeOS] Creating PR: ${BRANCH} → ${BASE_BRANCH}"

# 変更差分のサマリを生成
CHANGED_FILES=$(git diff --stat "${BASE_BRANCH}...${BRANCH}" 2>/dev/null || git diff --stat HEAD~1)
COMMIT_LOG=$(git log "${BASE_BRANCH}..${BRANCH}" --oneline 2>/dev/null || git log -5 --oneline)

PR_URL=$(gh pr create \
  --repo "$REPO" \
  --title "Auto PR: ${BRANCH}" \
  --body "$(cat <<EOF
## Summary
Auto-generated by ClaudeOS

## Changes
\`\`\`
${CHANGED_FILES}
\`\`\`

## Commits
\`\`\`
${COMMIT_LOG}
\`\`\`

## Test
- [ ] Unit tests passed
- [ ] Integration tests passed
- [ ] Lint passed
- [ ] Build succeeded

## CI
- Pending GitHub Actions verification
EOF
)" \
  --base "$BASE_BRANCH" \
  --head "$BRANCH" 2>&1)

echo "[ClaudeOS] PR created: ${PR_URL}"
