#!/bin/bash
# =============================================================================
# AEGIS-SIGHT - GitHub Issue 自動生成スクリプト
# ClaudeOS Dev Factory から呼び出される
# =============================================================================

set -euo pipefail

TITLE="${1:?Usage: create-issue.sh <TITLE> [BODY] [LABELS]}"
BODY="${2:-Auto-generated by ClaudeOS Dev Factory}"
LABELS="${3:-auto-generated}"
REPO="Kensan196948G/AEGIS-SIGHT"

echo "[ClaudeOS] Creating Issue: ${TITLE}"

ISSUE_URL=$(gh issue create \
  --repo "$REPO" \
  --title "$TITLE" \
  --body "$BODY" \
  --label "$LABELS" 2>&1)

echo "[ClaudeOS] Issue created: ${ISSUE_URL}"

# Issue番号を抽出して返す
ISSUE_NUMBER=$(echo "$ISSUE_URL" | grep -oP '\d+$')
echo "$ISSUE_NUMBER"
