#!/bin/bash
# =============================================================================
# AEGIS-SIGHT - 新規開発環境セットアップスクリプト
# GitHub Projects・ラベル・マイルストーン・初期Issueを一括セットアップする
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# 定数
# ---------------------------------------------------------------------------
REPO="Kensan196948G/AEGIS-SIGHT"
OWNER="Kensan196948G"
PROJECT_ROOT="/mnt/LinuxHDD/AEGIS-SIGHT"

# ---------------------------------------------------------------------------
# ヘルパー関数
# ---------------------------------------------------------------------------
log_info()  { echo "[ClaudeOS][SETUP][INFO]  $*"; }
log_warn()  { echo "[ClaudeOS][SETUP][WARN]  $*" >&2; }
log_error() { echo "[ClaudeOS][SETUP][ERROR] $*" >&2; }
log_ok()    { echo "[ClaudeOS][SETUP][OK]    $*"; }

# ---------------------------------------------------------------------------
# Step 1: gh auth 確認
# ---------------------------------------------------------------------------
log_info "=== Step 1: GitHub CLI Authentication ==="

if ! command -v gh &>/dev/null; then
  log_error "GitHub CLI (gh) is not installed."
  log_error "Install: https://cli.github.com/"
  exit 1
fi

if ! gh auth status &>/dev/null; then
  log_error "Not authenticated with GitHub CLI."
  log_error "Run: gh auth login"
  exit 1
fi

GH_USER=$(gh api user -q '.login' 2>/dev/null || echo "unknown")
log_ok "Authenticated as: ${GH_USER}"

# リポジトリアクセス確認
if ! gh repo view "$REPO" --json name &>/dev/null; then
  log_error "Cannot access repository: ${REPO}"
  exit 1
fi
log_ok "Repository accessible: ${REPO}"

# ---------------------------------------------------------------------------
# Step 2: GitHub Projects 確認・作成
# ---------------------------------------------------------------------------
log_info "=== Step 2: GitHub Projects ==="

EXISTING_PROJECT=$(gh project list --owner "$OWNER" --format json 2>/dev/null | \
  jq -r '.projects[] | select(.title | test("AEGIS")) | .number' 2>/dev/null | head -1 || echo "")

if [[ -n "$EXISTING_PROJECT" ]]; then
  log_ok "Project already exists: #${EXISTING_PROJECT}"
else
  log_info "Creating new GitHub Project..."
  NEW_PROJECT=$(gh project create --owner "$OWNER" --title "AEGIS-SIGHT Development Board" --format json 2>&1) || {
    log_warn "Could not create project (may require manual creation): $NEW_PROJECT"
  }
  if [[ -n "$NEW_PROJECT" ]]; then
    log_ok "Project created: $NEW_PROJECT"
  fi
fi

# ---------------------------------------------------------------------------
# Step 3: ラベル作成
# ---------------------------------------------------------------------------
log_info "=== Step 3: Labels ==="

declare -A LABELS=(
  # type
  ["enhancement"]="a2eeef:New feature or enhancement"
  ["bug"]="d73a4a:Bug fix"
  ["documentation"]="0075ca:Documentation only"
  ["refactor"]="fbca04:Code refactoring"
  ["chore"]="ededed:Maintenance tasks"
  # component
  ["backend"]="0e8a16:Backend (aegis-sight-api)"
  ["frontend"]="1d76db:Frontend (aegis-sight-web)"
  ["agent"]="5319e7:Agent (aegis-sight-agent)"
  ["infra"]="006b75:Infrastructure"
  ["ci"]="bfd4f2:CI/CD related"
  # priority
  ["P0-critical"]="b60205:Critical priority"
  ["P1-high"]="ff9f1c:High priority"
  ["P2-medium"]="fbca04:Medium priority"
  ["P3-low"]="c5def5:Low priority"
  # status
  ["WIP"]="fef2c0:Work in progress"
  ["review"]="d4c5f9:Ready for review"
  ["blocked"]="e99695:Blocked by dependency"
  # security
  ["security"]="ee0701:Security related"
  # auto
  ["auto-generated"]="c2e0c6:Auto-generated by ClaudeOS"
)

for label in "${!LABELS[@]}"; do
  IFS=':' read -r color description <<< "${LABELS[$label]}"
  if gh label create "$label" --repo "$REPO" --color "$color" --description "$description" 2>/dev/null; then
    log_ok "Label created: ${label}"
  else
    # ラベルが既に存在する場合は更新
    gh label edit "$label" --repo "$REPO" --color "$color" --description "$description" 2>/dev/null && \
      log_info "Label updated: ${label}" || \
      log_warn "Could not create/update label: ${label}"
  fi
done

# ---------------------------------------------------------------------------
# Step 4: マイルストーン作成
# ---------------------------------------------------------------------------
log_info "=== Step 4: Milestones ==="

declare -A MILESTONES=(
  ["Phase 1: Foundation"]="基盤構築 - API/Web/Agent のスケルトン, CI/CD, Docker, 認証基盤"
  ["Phase 2: Core Features"]="コア機能実装 - エンドポイント管理, ソフトウェア収集, ダッシュボード"
  ["Phase 3: IAMS Integration"]="IAMS統合 - Prometheus/Grafana, PWA, 調達管理, SAMライセンス"
  ["Phase 4: Production Ready"]="本番準備 - セキュリティ監査, パフォーマンス最適化, ドキュメント完備"
)

for title in "${!MILESTONES[@]}"; do
  description="${MILESTONES[$title]}"
  if gh api "repos/${REPO}/milestones" -f title="$title" -f description="$description" -f state="open" 2>/dev/null | jq -r '.number' &>/dev/null; then
    log_ok "Milestone created: ${title}"
  else
    log_info "Milestone may already exist: ${title}"
  fi
done

# ---------------------------------------------------------------------------
# Step 5: 初期 Issue 生成
# ---------------------------------------------------------------------------
log_info "=== Step 5: Initial Issues ==="

create_issue() {
  local title="$1"
  local body="$2"
  local labels="$3"

  EXISTING=$(gh issue list --repo "$REPO" --search "\"$title\" in:title" --json number -q '.[0].number' 2>/dev/null || echo "")
  if [[ -n "$EXISTING" ]]; then
    log_info "Issue already exists: #${EXISTING} - ${title}"
    return 0
  fi

  RESULT=$(gh issue create --repo "$REPO" --title "$title" --body "$body" --label "$labels" 2>&1) && \
    log_ok "Issue created: ${title} -> ${RESULT}" || \
    log_warn "Failed to create issue: ${title}"
}

create_issue \
  "[Phase1] Backend API スケルトン構築" \
  "FastAPI プロジェクト構造の作成\n- 認証・認可 (Azure AD)\n- ヘルスチェック\n- OpenAPI ドキュメント\n- Alembic マイグレーション基盤" \
  "enhancement,backend"

create_issue \
  "[Phase1] Frontend Next.js スケルトン構築" \
  "Next.js 14 App Router プロジェクト構造の作成\n- 認証フロー (MSAL)\n- レイアウト・ナビゲーション\n- テーマ・デザインシステム" \
  "enhancement,frontend"

create_issue \
  "[Phase1] CI/CD パイプライン構築" \
  "GitHub Actions ワークフローの作成\n- lint (ruff, eslint)\n- test (pytest, jest)\n- build (Docker)\n- deploy (staging/production)" \
  "enhancement,ci"

create_issue \
  "[Phase1] Docker Compose 開発環境整備" \
  "docker-compose.dev.yml の完備\n- PostgreSQL 16\n- Redis\n- API/Web ホットリロード\n- Volume マウント" \
  "enhancement,infra"

create_issue \
  "[Phase1] Agent PowerShell スケルトン構築" \
  "PowerShell 7.4 エージェント基盤\n- エンドポイント情報収集\n- API 通信モジュール\n- スケジュール実行\n- ログ出力" \
  "enhancement,agent"

# ---------------------------------------------------------------------------
# 完了
# ---------------------------------------------------------------------------
log_info "========================================="
log_info "Setup Complete!"
log_info "========================================="
log_info "Repository:  ${REPO}"
log_info "User:        ${GH_USER}"
log_info "Labels:      ${#LABELS[@]} configured"
log_info "Milestones:  ${#MILESTONES[@]} configured"
log_info "========================================="
