#!/bin/bash
# =============================================================================
# AEGIS-SIGHT - GitHub Labels 標準セット定義・作成スクリプト
# カテゴリ別にラベルを一括作成・更新する
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# 定数
# ---------------------------------------------------------------------------
REPO="Kensan196948G/AEGIS-SIGHT"

# ---------------------------------------------------------------------------
# ヘルパー関数
# ---------------------------------------------------------------------------
log_info()  { echo "[ClaudeOS][LABELS][INFO]  $*"; }
log_ok()    { echo "[ClaudeOS][LABELS][OK]    $*"; }
log_warn()  { echo "[ClaudeOS][LABELS][WARN]  $*" >&2; }

usage() {
  cat <<USAGE
Usage: setup-labels.sh [--delete-defaults] [--dry-run]

Options:
  --delete-defaults  GitHub デフォルトラベルを削除してからセットアップ
  --dry-run          実際には作成せず、プレビューのみ

標準ラベルセットを作成・更新します。

カテゴリ:
  type:       feat, fix, docs, refactor, chore, test, perf, security
  component:  backend, frontend, agent, infra, ci
  priority:   P0-critical, P1-high, P2-medium, P3-low
  status:     WIP, review, blocked, ready
USAGE
  exit 1
}

# ---------------------------------------------------------------------------
# オプション解析
# ---------------------------------------------------------------------------
DELETE_DEFAULTS=false
DRY_RUN=false

for arg in "$@"; do
  case "$arg" in
    --delete-defaults) DELETE_DEFAULTS=true ;;
    --dry-run) DRY_RUN=true ;;
    -h|--help) usage ;;
  esac
done

# ---------------------------------------------------------------------------
# ラベル定義
# ---------------------------------------------------------------------------
# Format: "name|color|description"

TYPE_LABELS=(
  "type:feat|a2eeef|New feature or enhancement"
  "type:fix|d73a4a|Bug fix"
  "type:docs|0075ca|Documentation"
  "type:refactor|fbca04|Code refactoring"
  "type:chore|ededed|Maintenance / chore"
  "type:test|bfd4f2|Test improvements"
  "type:perf|f9d0c4|Performance improvement"
  "type:security|ee0701|Security fix or improvement"
)

COMPONENT_LABELS=(
  "component:backend|0e8a16|Backend (aegis-sight-api / FastAPI)"
  "component:frontend|1d76db|Frontend (aegis-sight-web / Next.js)"
  "component:agent|5319e7|Agent (aegis-sight-agent / PowerShell)"
  "component:infra|006b75|Infrastructure (Docker / Prometheus / Grafana)"
  "component:ci|bfd4f2|CI/CD (GitHub Actions / Scripts)"
)

PRIORITY_LABELS=(
  "priority:P0-critical|b60205|Critical - Production outage or security vulnerability"
  "priority:P1-high|ff9f1c|High - Major feature or important bug"
  "priority:P2-medium|fbca04|Medium - Standard feature or minor bug"
  "priority:P3-low|c5def5|Low - Nice to have"
)

STATUS_LABELS=(
  "status:WIP|fef2c0|Work in progress"
  "status:review|d4c5f9|Ready for code review"
  "status:blocked|e99695|Blocked by external dependency"
  "status:ready|0e8a16|Ready to merge / deploy"
)

# 短縮名ラベル（auto-label.sh との互換性）
COMPAT_LABELS=(
  "enhancement|a2eeef|New feature or enhancement"
  "bug|d73a4a|Bug report or fix"
  "documentation|0075ca|Documentation"
  "refactor|fbca04|Code refactoring"
  "backend|0e8a16|Backend related"
  "frontend|1d76db|Frontend related"
  "agent|5319e7|Agent related"
  "infra|006b75|Infrastructure related"
  "ci|bfd4f2|CI/CD related"
  "security|ee0701|Security related"
  "auto-generated|c2e0c6|Auto-generated by ClaudeOS"
  "chore|ededed|Maintenance tasks"
)

ALL_LABELS=(
  "${TYPE_LABELS[@]}"
  "${COMPONENT_LABELS[@]}"
  "${PRIORITY_LABELS[@]}"
  "${STATUS_LABELS[@]}"
  "${COMPAT_LABELS[@]}"
)

# ---------------------------------------------------------------------------
# GitHub デフォルトラベルの削除（オプション）
# ---------------------------------------------------------------------------
if [[ "$DELETE_DEFAULTS" == "true" ]]; then
  log_info "Removing GitHub default labels..."
  DEFAULT_LABELS=("bug" "duplicate" "enhancement" "good first issue" "help wanted" "invalid" "question" "wontfix")
  for label in "${DEFAULT_LABELS[@]}"; do
    if [[ "$DRY_RUN" == "true" ]]; then
      log_info "[DRY-RUN] Would delete: ${label}"
    else
      gh label delete "$label" --repo "$REPO" --yes 2>/dev/null && \
        log_info "Deleted default: ${label}" || true
    fi
  done
fi

# ---------------------------------------------------------------------------
# ラベル作成・更新
# ---------------------------------------------------------------------------
CREATED=0
UPDATED=0
SKIPPED=0
ERRORS=0

log_info "Setting up ${#ALL_LABELS[@]} labels for ${REPO}..."

for entry in "${ALL_LABELS[@]}"; do
  IFS='|' read -r name color description <<< "$entry"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "[DRY-RUN] Would create: ${name} (#${color}) - ${description}"
    continue
  fi

  # 作成を試みる
  if gh label create "$name" --repo "$REPO" --color "$color" --description "$description" 2>/dev/null; then
    log_ok "Created: ${name}"
    CREATED=$((CREATED + 1))
  else
    # 既に存在する場合は更新
    if gh label edit "$name" --repo "$REPO" --color "$color" --description "$description" 2>/dev/null; then
      log_info "Updated: ${name}"
      UPDATED=$((UPDATED + 1))
    else
      log_warn "Failed: ${name}"
      ERRORS=$((ERRORS + 1))
    fi
  fi
done

# ---------------------------------------------------------------------------
# サマリ
# ---------------------------------------------------------------------------
log_info "========================================="
log_info "Label Setup Summary"
log_info "========================================="
if [[ "$DRY_RUN" == "true" ]]; then
  log_info "Mode:    DRY-RUN (no changes made)"
fi
log_info "Total:   ${#ALL_LABELS[@]}"
log_info "Created: ${CREATED}"
log_info "Updated: ${UPDATED}"
log_info "Errors:  ${ERRORS}"
log_info "========================================="

# カテゴリ別一覧
log_info ""
log_info "Label Categories:"
log_info "  type:       ${#TYPE_LABELS[@]} labels"
log_info "  component:  ${#COMPONENT_LABELS[@]} labels"
log_info "  priority:   ${#PRIORITY_LABELS[@]} labels"
log_info "  status:     ${#STATUS_LABELS[@]} labels"
log_info "  compat:     ${#COMPAT_LABELS[@]} labels"
